fimak_site_index:
    pattern:  /
    defaults: { _controller: FimakSiteBundle:Default:index }

fimak_site_about:
    pattern: /about
    defaults: { _controller: FimakSiteBundle:Default:about }

fimak_site_contact:
    pattern: /contact
    defaults: { _controller: FimakSiteBundle:Default:contact }
    requirements:
        _method:  GET|POST

fimak_site_articles:
    pattern: /articles
    defaults: { _controller: FimakSiteBundle:Article:index }

fimak_site_article_view:
    pattern: /article/{id}/{slug}/{comments}
    defaults: { _controller: FimakSiteBundle:Article:view, comments: true }
    requirements:
        _method: GET
        id: \d+

fimak_site_comment_create:
    pattern: /comment/{article_id}
    defaults: { _controller: FimakSiteBundle:Comment:create }
    requirements:
        _method: POST
        article_id: \d+
