parameters:
#    fimak_site.example.class: Fimak\SiteBundle\Example

services:
#    fimak_site.example:
#        class: %fimak_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
